apiVersion: apps/v1
kind: Deployment
metadata:
  name: Employe-frontend
  namespace: job
  labels:
    global: logic
spec:
  replicas: 1
  selector: 
    matchLabels:
      global: logic
  template:
    metadata:
      name: Employe-frontend
      labels:
        global: logic
    spec:
      containers:
        - name: Employee_f
          image: shubhamdoc0705/frontend:latest
          ports:
            containerPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Employe-backend
  namespace: job
  labels:
    global: logic-b
spec: 
  replicas: 1
  selector:
    matchLabels:
      global: logic-b
  template:
    metadata:
      name: Employe-backend
      labels:
        global: logic-b
    spec: 
      containers:
        - name: Employee-b
          image: shubhamdoc0705/backend:latest
          ports:
            containerPort: 5000
