apiVersion: apps/v1
kind: Deployment
metadata:
  name: Employe
  namespacce: job
  labels:
    global: logic
spec:
  replicas: 1
  selector: 
  matchLable:
    global: logic
  tamplate:
    metadata:
      name: Employe
      labels:
        global: logic
    spec:
      containers:
        - name: Employee
          image: shubhamdoc0705/frontend:latest
          port:
            containerPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Employe-backend
  namespacce: job
  labels:
    global: logic-b
spec: 
  replicas: 1
  selector:
  matchLable:
    global: logic-b
  tamplate:
    metadata:
      name: Employe-backend
      labels:
        global: logic-b
    spec: 
      containers:
        - name: Employee-b
          image: shubhamdoc0705/backend:latest
          port:
            containerPort: 5000
